### ISSUE TITLE
Interpolation issues with suferplots

### ISSUE THREAD

**Issue by SamRobinson113** [Bartesto/rivRmon#4]
There is a problem with the plot output for the Canning at ELL with the 28/10/2019 data showing a white band in the DO plot where it should be orange.
[canning_2019-10-29_surfer.pdf](https://github.com/Bartesto/rivRmon/files/3796336/canning_2019-10-29_surfer.pdf)

**Comment by Bartesto** [comment]
Issue is probably related to nearby site driving the very low (out of range) value at ELL. Possible solutions include giving users more freedom in assignment of interpolation method.

Will look at adding this functionality in next development cycle.

@SamRobinson113 can you please add the raw data file so that this can be recreated and tested later on. Thnx

**Comment by SamRobinson113** [comment]
[20191029coEXO3.xlsx](https://github.com/Bartesto/rivRmon/files/3796662/20191029coEXO3.xlsx)
[20191029cEXO3.xlsx](https://github.com/Bartesto/rivRmon/files/3796663/20191029cEXO3.xlsx)

**Comment by Bartesto** [comment]
Two issues here. 

White band/blob created by error in colour ramps where values were outside of available colours, which has now been fixed.

Interpolations are harder to work with. Kriging produces sub-optimal results. No easy way to incorporate changes in anistropy without doing a proper step by step modelling which is outside the scope of these visualisations without overcomplication.

Have rolled out a new feature whereby the river bottom is adjusted to bottom values in data. This has had the effect of removing some of those erroneous interpolations below measured values.
